package org.sonarsource.kotlin.checks

class AllBranchesIdenticalCheckTest : SimpleCheckTest(AllBranchesIdenticalCheck())
class BadClassNameCheckTest : SimpleCheckTest(BadClassNameCheck())
class BadFunctionNameCheckTest : SimpleCheckTest(BadFunctionNameCheck())
class BooleanInversionCheckTest : SimpleCheckTest(BooleanInversionCheck())
class BooleanLiteralCheckTest : SimpleCheckTest(BooleanLiteralCheck())
class CipherBlockChainingCheckTest : SimpleCheckTest(CipherBlockChainingCheck())
class ClearTextProtocolCheckTest : SimpleCheckTest(ClearTextProtocolCheck())
class CodeAfterJumpCheckTest : SimpleCheckTest(CodeAfterJumpCheck())
class CollapsibleIfStatementsCheckTest : SimpleCheckTest(CollapsibleIfStatementsCheck())
class CommentedCodeCheckTest : SimpleCheckTest(CommentedCodeCheck())
class DataHashingCheckTest : SimpleCheckTest(DataHashingCheck())
class DuplicateBranchCheckTest : SimpleCheckTest(DuplicateBranchCheck())
class DuplicatedFunctionImplementationCheckTest : SimpleCheckTest(DuplicatedFunctionImplementationCheck())
class ElseIfWithoutElseCheckTest : SimpleCheckTest(ElseIfWithoutElseCheck())
class EmptyBlockCheckTest : SimpleCheckTest(EmptyBlockCheck())
class EmptyCommentCheckTest : SimpleCheckTest(EmptyCommentCheck())
class EmptyFunctionCheckTest : SimpleCheckTest(EmptyFunctionCheck())
class EncryptionAlgorithmCheckTest : SimpleCheckTest(EncryptionAlgorithmCheck())
class FixMeCommentCheckTest : SimpleCheckTest(FixMeCommentCheck())
class FunctionCognitiveComplexityCheckTest : SimpleCheckTest(FunctionCognitiveComplexityCheck().apply { threshold = 4 })
class HardcodedCredentialsCheckTest : SimpleCheckTest(HardcodedCredentialsCheck())
class HardcodedIpCheckTest : SimpleCheckTest(HardcodedIpCheck())
class IdenticalBinaryOperandCheckTest : SimpleCheckTest(IdenticalBinaryOperandCheck())
class IdenticalConditionsCheckTest : SimpleCheckTest(IdenticalConditionsCheck())
class IfConditionalAlwaysTrueOrFalseCheckTest : SimpleCheckTest(IfConditionalAlwaysTrueOrFalseCheck())
class MatchCaseTooBigCheckTest : SimpleCheckTest(MatchCaseTooBigCheck())
class NestedMatchCheckTest : SimpleCheckTest(NestedMatchCheck())
class OneStatementPerLineCheckTest : SimpleCheckTest(OneStatementPerLineCheck())
class PseudoRandomCheckTest : SimpleCheckTest(PseudoRandomCheck())
class RedundantParenthesesCheckTest : SimpleCheckTest(RedundantParenthesesCheck())
class RobustCryptographicKeysCheckTest : SimpleCheckTest(RobustCryptographicKeysCheck())
class SelfAssignmentCheckTest : SimpleCheckTest(SelfAssignmentCheck())
class ServerCertificateCheckTest : SimpleCheckTest(ServerCertificateCheck())
class StringLiteralDuplicatedCheckTest : SimpleCheckTest(StringLiteralDuplicatedCheck())
class StrongCipherAlgorithmCheckTest : SimpleCheckTest(StrongCipherAlgorithmCheck())
class TabsCheckTest : SimpleCheckTest(TabsCheck(), sampleFileNoSemantics = "DummyNoIssues.kt")
class TodoCommentCheckTest : SimpleCheckTest(TodoCommentCheck())
class TooComplexExpressionCheckTest : SimpleCheckTest(TooComplexExpressionCheck())
class TooDeeplyNestedStatementsCheckTest : SimpleCheckTest(TooDeeplyNestedStatementsCheck().apply { max = 1 })
class TooLongFunctionCheckTest : SimpleCheckTest(TooLongFunctionCheck().apply { max = 3 })
class TooLongLineCheckTest : SimpleCheckTest(TooLongLineCheck())
class TooManyCasesCheckTest : SimpleCheckTest(TooManyCasesCheck().apply { maximum = 2 })
class TooManyParametersCheckTest : SimpleCheckTest(TooManyParametersCheck().apply { max = 2 })
class UnusedFunctionParameterCheckTest : SimpleCheckTest(UnusedFunctionParameterCheck())
class UnusedLocalVariableCheckTest : SimpleCheckTest(UnusedLocalVariableCheck())
class UnusedPrivateMethodCheckTest : SimpleCheckTest(UnusedPrivateMethodCheck())
class VariableAndParameterNameCheckTest : SimpleCheckTest(VariableAndParameterNameCheck().apply { format = "^[_a-z][a-zA-Z0-9]*$" })
class VerifiedServerHostnamesCheckTest : SimpleCheckTest(VerifiedServerHostnamesCheck())
class WeakSSLContextCheckTest : SimpleCheckTest(WeakSSLContextCheck())
class WrongAssignmentOperatorCheckTest : SimpleCheckTest(WrongAssignmentOperatorCheck())
