name: dogfood merge
# This workflow is triggered on pushes to master and dogfood branches
on:
  push:
    branches:
      - master
      - 'dogfood/**'

env:
  SLACK_USERNAME: Dogfood build action

jobs:
  dogfood_merge:
    runs-on: ubuntu-latest
    name: Update dogfood branch
    permissions:
      id-token: write # required for SonarSource/vault-action-wrapper
    steps:
      - name: get secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@dc8fe04652687f7278f3ecd27905967836bab0eb  # tag=2.7.4-1
        with:
          secrets: |
            development/kv/data/slack webhook | SLACK_WEBHOOK;
            development/github/token/{REPO_OWNER_NAME_DASH}-dogfood-merge token | dogfood_token;
      - name: git octopus step
        env:
          GITHUB_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).dogfood_token }}
        id: dogfood
        uses: SonarSource/gh-action_dogfood_merge@v1
        with:
          dogfood-branch: 'dogfood-on-peach'
      # Use the output from the `dogfood` step
      - name: Get the name of the dogfood branch and its HEAD SHA1
        run: echo "The dogfood branch was `${{ steps.dogfood.outputs.dogfood-branch }}` and its HEAD SHA1 was `${{ steps.dogfood.outputs.sha1 }}`"
      #slack notifications
      - name: Notify failures on Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,author,eventName
          channel: '#team-lang-kotlin'
        env:
          SLACK_WEBHOOK_URL: ${{ fromJSON(steps.secrets.outputs.vault).SLACK_WEBHOOK }}
